# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    # - context: django-spanner
    - image: gcr.io/innate-bonfire-361004/django-spanner-nombre-gke
      docker:
        dockerfile: Dockerfile
        buildArgs:
          PORT: "8080"
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
      - gke/dev/**.yaml
# use the cloudbuild profile to build images using Google Cloud Build
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
